added Fuzzer to send udp commands
tjlaekem/fozzy pull request #6
Opened 2017-07-24 03:36 UTC by fred-he

2017-07-27 15:05 UTC, taylorlaekeman requested changes
this code is based on an old version of the source code, I think it needs to be updated to fit with the system as it is now

2017-08-05 02:01 UTC, njjewers requested changes
Did you build and test this?

2017-08-05 02:01 UTC, njjewers commented on src/Fozzie.java
> -      System.out.println(i + " " + CommandFactory.makeCommand());
Removing this line means that the command never regenerates, tight? You're just sending the same command over and over again

2017-08-05 02:01 UTC, njjewers commented on src/Fozzie.java
> +      String commandString = CommandFactory.makeCommand(CommandFactory.CommandType.valueof(cmd), boolean valid!=0).toString();
Move this block to the while loop so the command will be regenerated

2017-08-05 02:01 UTC, njjewers commented on src/Fozzie.java
> +  private static final String SAFE_MODE = "AT*PCMD=1,0,0,0,0,0\r"; // PCMD hovering mode
IMO this should be "AT*REF=1,290717696\rAT*PCMD=1,0,0,0,0,0\r" - including the ref command is better parity with the app, and counteracts bad ref commands.

2017-08-05 02:01 UTC, njjewers commented on src/Fozzie.java
> +    catch (Exception e) {
There are only 3 args, IMO we should just print a usage message and die if there are no/bad args

2017-08-05 02:01 UTC, njjewers commented on src/Fozzie.java
> +  	DatagramSocket serverSocket = new DatagramSocket(RECEIVE_PORT);
This doesn't work, yeah? might as well remove it and all other code related to it

2017-08-05 02:01 UTC, njjewers commented on src/Fozzie.java
> +  	}
Nix 69-84, seeing as they don't work

2017-08-05 02:01 UTC, njjewers commented on src/Fozzie.java
> +  	}
likewise just replace this with a single thread.sleep

2017-08-05 17:37 UTC, tjlaekem commented on src/Fuzzer.java
> +public class Fuzzer {
This is just a duplicate of Fozzie.java, right?  Can we delete this file?

2017-08-05 20:20 UTC, fred-he commented on src/Fuzzer.java
> +public class Fuzzer {
yes

2017-08-05 20:24 UTC, fred-he commented on src/Fozzie.java
> +      String commandString = CommandFactory.makeCommand(CommandFactory.CommandType.valueof(cmd), boolean valid!=0).toString();
? @njjewers

2017-08-08 03:18 UTC, merged